- project:
    queue: solum
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - solum-devstack-yoga
        - solum-devstack-xena
        - solum-devstack-wallaby

- job:
    name: solum-devstack-zed
    parent: solum-devstack
    nodeset: openstack-single-node-focal
    override-checkout: stable/zed

- job:
    name: solum-devstack-yoga
    parent: solum-devstack
    nodeset: openstack-single-node-focal
    override-checkout: stable/yoga

- job:
    name: solum-devstack-xena
    parent: solum-devstack
    nodeset: openstack-single-node-focal
    override-checkout: stable/xena

- job:
    name: solum-devstack-wallaby
    parent: solum-devstack
    nodeset: openstack-single-node-focal
    override-checkout: stable/wallaby
