- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - solum-devstack-yoga
        - solum-devstack-xena
        - solum-devstack-wallaby
        - solum-devstack-victoria
    gate:
      queue: solum

- job:
    name: solum-devstack-yoga
    parent: solum-devstack
    nodeset: openstack-single-node-focal
    override-checkout: stable/yoga

- job:
    name: solum-devstack-xena
    parent: solum-devstack
    nodeset: openstack-single-node-focal
    override-checkout: stable/xena

- job:
    name: solum-devstack-wallaby
    parent: solum-devstack
    nodeset: openstack-single-node-focal
    override-checkout: stable/wallaby

- job:
    name: solum-devstack-victoria
    parent: solum-devstack
    nodeset: openstack-single-node-focal
    override-checkout: stable/victoria
